- name: Install VirtualBox and Vagrant on Ubuntu 20.04
  hosts: localhost
  become: true

  tasks:
    - name: Add VirtualBox repository key
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present

    - name: Add VirtualBox repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian focal contrib"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install VirtualBox
      apt:
        name: virtualbox-6.1
        state: present

    - name: Install Vagrant dependencies
      apt:
        name:
          - wget
          - gnupg
        state: present

    - name: Add HashiCorp repository key
      shell: wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      changed_when: false

    - name: Add HashiCorp repository
      shell: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      changed_when: false

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Vagrant
      apt:
        name: vagrant
        state: present
